// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoPortcullis.h"
#include "../Subsystems/PneumaticSub.h"
#include "../Subsystems/Chassis.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoPortcullis::AutoPortcullis(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	SetTimeout(8);
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoPortcullis::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void AutoPortcullis::Execute() {
	printf("Lowering defense\n");
	Robot::pneumaticSub->GetDefenseSolenoid()->Set(true);
	Wait(5);
	printf("Starting to drive forward\n");
	Robot::chassis->driveFeet(10, 0.5);
}

// Make this return true when this Command no longer needs to run execute()
bool AutoPortcullis::IsFinished() {
    return IsTimedOut();
}

// Called once after isFinished returns true
void AutoPortcullis::End() {
	Robot::pneumaticSub->GetDefenseSolenoid()->Set(false);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoPortcullis::Interrupted() {

}
