// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveCmd.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveCmd::DriveCmd(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void DriveCmd::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void DriveCmd::Execute() {
	Robot::chassis->DriveWithJoysticks();
	if (Robot::oi->getrightJoy()->GetRawButton(3) && Robot::oi->getleftJoy()->GetRawButton(3)) {
		Robot::chassis->GShift();
	}
	if (Robot::oi->getrightJoy()->GetRawButton(1) && Robot::oi->getleftJoy()->GetRawButton(1)){
		Robot::chassis->InvertMotors();
	}
	Robot::chassis->PrintValues();
}

// Make this return true when this Command no longer needs to run execute()
bool DriveCmd::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void DriveCmd::End() {
	// Robot::chassis->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveCmd::Interrupted() {
	End();
}
