// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveCmd.h"
#include "Commands/PickyUppy.h"
#include "Commands/ShootCmd.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    rightJoy.reset(new Joystick(1));
    
    leftJoy.reset(new Joystick(0));
    
    gamepad.reset(new Joystick(2));
    

    // SmartDashboard Buttons
    SmartDashboard::PutData("ShootCmd", new ShootCmd());
    SmartDashboard::PutData("PickyUppy", new PickyUppy());
    SmartDashboard::PutData("DriveCmd", new DriveCmd());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getGamepad() {
   return gamepad;
}

std::shared_ptr<Joystick> OI::getleftJoy() {
   return leftJoy;
}

std::shared_ptr<Joystick> OI::getrightJoy() {
   return rightJoy;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
