// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Joystick> rightJoy;
	std::shared_ptr<JoystickButton> climb11;
	std::shared_ptr<Joystick> leftJoy;
	std::shared_ptr<Joystick> gamepad;
	std::shared_ptr<JoystickButton> holdBoulder;
	std::shared_ptr<JoystickButton> lowGoal4;
	std::shared_ptr<JoystickButton> highGoal1;
	std::shared_ptr<JoystickButton> scissorlift8;
	std::shared_ptr<JoystickButton> defense5;
	std::shared_ptr<JoystickButton> ratchet2;
	std::shared_ptr<JoystickButton> alignButton;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	void addButton();
	std::shared_ptr<Joystick> getGamepad();
	std::shared_ptr<Joystick> getleftJoy();
	std::shared_ptr<Joystick> getrightJoy();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
